id: postgres
name: PostgreSQL
produces: tcp
backend: terraform

inputs:
  project_id: "{{ nclav_project_id }}"
  region: "{{ nclav_region }}"

declared_outputs:
  - hostname
  - port
  - db_name
  - db_user
  - db_password
  - psc_service_attachment
