id: product-a-dev
name: Product A (Development)
cloud: local
region: local-1
identity: product-a-dev-identity
network:
  vpc_cidr: "10.0.0.0/16"
  subnets:
    - "10.0.1.0/24"
    - "10.0.2.0/24"
dns:
  zone: product-a.dev.local
exports:
  - name: api-http
    target_partition: api
    type: http
    to: any_enclave
    auth: token
  - name: db-tcp
    target_partition: db
    type: tcp
    to: any_enclave
    auth: none
imports: []
